<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JyotiLappy" ignored="0" name="functional test(failed)" tests="5" failures="3" timestamp="02 Apr 2019 15:16:24 GMT" time="92.53" errors="0">
  <testcase name="loginTest" time="5.736" classname="com.PracticeProject.testCases.TC_loginTest_001"/>
  <testcase name="LoginDataDrivenTest" time="12.047" classname="com.PracticeProject.testCases.TC_LoginDataDrivenTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.PracticeProject.testCases.TC_LoginDataDrivenTest_002.LoginDataDrivenTest(TC_LoginDataDrivenTest_002.java:41)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDataDrivenTest -->
  <testcase name="LoginDataDrivenTest" time="8.937" classname="com.PracticeProject.testCases.TC_LoginDataDrivenTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.PracticeProject.testCases.TC_LoginDataDrivenTest_002.LoginDataDrivenTest(TC_LoginDataDrivenTest_002.java:41)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDataDrivenTest -->
  <testcase name="LoginDataDrivenTest" time="31.157" classname="com.PracticeProject.testCases.TC_LoginDataDrivenTest_002"/>
  <testcase name="LoginDataDrivenTest" time="6.908" classname="com.PracticeProject.testCases.TC_LoginDataDrivenTest_002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.PracticeProject.testCases.TC_LoginDataDrivenTest_002.LoginDataDrivenTest(TC_LoginDataDrivenTest_002.java:41)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- LoginDataDrivenTest -->
</testsuite> <!-- functional test(failed) -->
